"""
Team Analysis — Build-up Pass Map

4-column layout:
  Col 1 (filter panel) | Col 2-3 (interactive Plotly pass map) | Col 4 (stats panel)

Filter controls generated by PassMap.dash_controls().
Callbacks registered via register_buildup_callbacks(app).
"""

import io
import base64

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from mplsoccer import Pitch

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import plotly.graph_objects as go
from dash import html, dcc, Input, Output, State
import dash_bootstrap_components as dbc

from utils.config import COLORS
from utils.data_utils import get_all_events, CURRENT_SEASON
from page_utils import PassMap, GOLD, HOME_COLOR, AWAY_COLOR
from page_utils.competitions import normalize_competitions as _normalize_competitions
from page_utils.event_filters import SHOT_TYPES as _SHOT_TYPES
from page_utils.visualizations import render_lsc_heatmap_img


# =============================================================================
# Pitch constants (inlined from page_utils/visualizations.py)
# =============================================================================

PITCH_BG         = '#151932'
PITCH_LINE_COLOR = '#8899CC'
BARCA_BLUE       = COLORS['primary_blue']
CYAN             = '#22D3EE'

PITCH_AXIS_FULL = dict(
    xaxis=dict(range=[-5, 105], showgrid=False, zeroline=False,
               showticklabels=False, fixedrange=True, visible=False),
    yaxis=dict(range=[-2, 102], showgrid=False, zeroline=False,
               showticklabels=False, fixedrange=True, visible=False,
               scaleanchor='x', scaleratio=0.68),
)

_PITCH_CACHE: dict = {}

CHART_CONFIG = {'displayModeBar': False}

_ENTRY_COLORS = {
    'Pass':    '#32cd32',
    'Dribble': '#ffa500',
    'Carry':   '#00bfff',
}

_ZONE14_COLORS = {
    'Zone 14':          '#ff1493',
    'Left Half Space':  '#00ffff',
    'Right Half Space': '#ffd700',
}


def _generate_pitch_image() -> str:
    """Generate a full grass pitch PNG via mplsoccer and return as base64."""
    if 'full' in _PITCH_CACHE:
        return _PITCH_CACHE['full']

    pitch = Pitch(
        pitch_type='opta', pitch_color=PITCH_BG, line_color=PITCH_LINE_COLOR,
        linewidth=2.5, stripe=False, goal_type='box', goal_alpha=0.8,
        pad_top=1, pad_bottom=1, pad_left=4, pad_right=4,
    )
    fig_mpl, _ = pitch.draw(figsize=(16, 10))
    buf = io.BytesIO()
    fig_mpl.savefig(buf, format='png', dpi=100, bbox_inches='tight', pad_inches=0)
    buf.seek(0)
    _PITCH_CACHE['full'] = base64.b64encode(buf.read()).decode()
    plt.close(fig_mpl)
    return _PITCH_CACHE['full']


def _add_pitch_background(fig: go.Figure) -> None:
    img = _generate_pitch_image()
    fig.add_layout_image(dict(
        source=f'data:image/png;base64,{img}',
        xref='x', yref='y',
        x=-5, y=102, sizex=110, sizey=104,
        sizing='stretch', opacity=1, layer='below',
    ))


def _add_attack_direction(fig: go.Figure) -> None:
    fig.add_annotation(
        x=0.5, y=1.02, xref='paper', yref='paper',
        text='<b>➡  Direction of Attack</b>',
        showarrow=False,
        font=dict(size=10, color='white', family='Arial, sans-serif'),
        xanchor='center', yanchor='bottom',
        bgcolor='rgba(21,25,50,0.8)',
        bordercolor=PITCH_LINE_COLOR,
        borderwidth=1, borderpad=4,
    )


def _build_pass_fig(passes: pd.DataFrame) -> go.Figure:
    """Build an interactive Plotly pass map from a filtered passes DataFrame."""
    fig = go.Figure()
    _add_pitch_background(fig)

    if len(passes) > 0 and 'Pass End X' in passes.columns:
        xs = passes['x'].values.astype(float)
        ys = passes['y'].values.astype(float)
        xe = passes['Pass End X'].values.astype(float)
        ye = passes['Pass End Y'].values.astype(float)

        has_outcome = 'outcome' in passes.columns
        outcomes    = passes['outcome'].values.astype(int) if has_outcome else np.ones(len(xs), dtype=int)

        mask_suc  = (outcomes == 1)
        mask_fail = ~mask_suc

        def _add_lines(mask, color, opacity_lines, opacity_dots):
            if not mask.any():
                return
            idx = np.where(mask)[0]
            x_seg, y_seg = [], []
            for i in idx:
                x_seg += [float(xs[i]), float(xe[i]), None]
                y_seg += [float(ys[i]), float(ye[i]), None]
            fig.add_trace(go.Scatter(
                x=x_seg, y=y_seg, mode='lines',
                line=dict(color=color, width=1.5),
                opacity=opacity_lines,
                showlegend=False, hoverinfo='skip',
            ))
            # Start dots
            fig.add_trace(go.Scatter(
                x=xs[mask], y=ys[mask], mode='markers',
                marker=dict(color=color, size=4, opacity=0.5, line=dict(width=0)),
                showlegend=False, hoverinfo='skip',
            ))
            # End dots (brighter)
            fig.add_trace(go.Scatter(
                x=xe[mask], y=ye[mask], mode='markers',
                marker=dict(color=color, size=6, line=dict(color='white', width=0.5)),
                opacity=opacity_dots,
                showlegend=False, hoverinfo='skip',
            ))

        _add_lines(mask_fail, COLORS['garnet'], opacity_lines=0.45, opacity_dots=0.65)
        _add_lines(mask_suc,  COLORS['gold'],   opacity_lines=0.75, opacity_dots=0.95)


    fig.update_layout(
        **PITCH_AXIS_FULL,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font=dict(color='#E8E9ED', size=12, family='Arial, sans-serif'),
        margin=dict(l=0, r=0, t=36, b=0),
        showlegend=False,
        height=520,
        uirevision='buildup-pass-map',
    )
    _add_attack_direction(fig)

    # Third dividers
    for x_pos, label in ((100/3, 'Def Third'), (200/3, 'Att Third')):
        fig.add_shape(type='line',
            x0=x_pos, x1=x_pos, y0=-2, y1=102,
            xref='x', yref='y',
            line=dict(color='rgba(255,255,255,0.20)', width=1.5, dash='dash'),
            layer='above',
        )
        fig.add_annotation(
            x=x_pos, y=103, xref='x', yref='y',
            text=f'<b>{label}</b>',
            showarrow=False,
            font=dict(size=8, color='rgba(255,255,255,0.40)', family='Arial, sans-serif'),
            xanchor='center', yanchor='bottom',
        )

    return fig


# =============================================================================
# Data helpers
# =============================================================================

def _get_passes(events: pd.DataFrame) -> pd.DataFrame:
    """Extract Barcelona pass rows with valid endpoint coordinates."""
    bar    = events[events['team_code'] == 'BAR']
    passes = bar[
        (bar['event_type'] == 'Pass') &
        bar['x'].notna() & bar['y'].notna()
    ].copy()

    if 'Pass End X' not in passes.columns or 'Pass End Y' not in passes.columns:
        return passes

    passes['Pass End X'] = pd.to_numeric(passes['Pass End X'], errors='coerce')
    passes['Pass End Y'] = pd.to_numeric(passes['Pass End Y'], errors='coerce')
    return passes[passes['Pass End X'].notna() & passes['Pass End Y'].notna()]


def _apply_filters(passes, *, outcomes, start_thirds, end_thirds,
                   bands, players, h1_range, h2_range) -> pd.DataFrame:
    passes = PassMap.filter(
        passes,
        outcomes=outcomes, start_thirds=start_thirds, end_thirds=end_thirds,
        bands=bands, h1_range=h1_range, h2_range=h2_range,
        end_x_col='Pass End X',
    )
    if players and 'player_name' in passes.columns:
        passes = passes[passes['player_name'].isin(players)]
    return passes


# =============================================================================
# Layout helpers
# =============================================================================

_LABEL_STYLE = {
    'color': GOLD,
    'fontSize': '0.70rem',
    'fontWeight': '700',
    'letterSpacing': '0.8px',
    'textTransform': 'uppercase',
    'marginBottom': '5px',
    'marginTop': '14px',
}

_PANEL_STYLE = {
    'backgroundColor': COLORS['dark_secondary'],
    'border': f'1px solid {COLORS["dark_border"]}',
    'borderRadius': '6px',
    'padding': '14px 12px',
    'overflowY': 'auto',
    'maxHeight': '80vh',
}

_SECTION_TITLE = {
    'color': GOLD,
    'fontWeight': '700',
    'fontSize': '0.82rem',
    'letterSpacing': '1px',
    'textTransform': 'uppercase',
    'paddingBottom': '8px',
    'borderBottom': f'1px solid {COLORS["dark_border"]}',
}


def _filter_panel(player_options=None) -> html.Div:
    return html.Div([
        html.Div("Filters", style=_SECTION_TITLE),

        html.Div("Player", style=_LABEL_STYLE),
        dcc.Dropdown(
            id='buildup-player-filter',
            options=player_options or [],
            value=None,
            multi=True,
            placeholder="All players…",
            style={'fontSize': '0.75rem'},
        ),

        *PassMap.dash_controls(
            show=['outcome', 'start_third', 'end_third', 'bands', 'h1_time', 'h2_time'],
            id_prefix='buildup',
        ),
    ], style=_PANEL_STYLE)


_X_BOUNDS = [0, 100/3, 200/3, 100]
_Y_BOUNDS  = [0, 100/3, 200/3, 100]


def _build_zone_pitch_image(passes: pd.DataFrame, n_total: int) -> str:
    """3×3 zone pitch: gold = % passes sent from zone, white = % received.
    n_total is the denominator (total passes in selected matches, pre-filter).
    """
    pitch = Pitch(
        pitch_type='opta', pitch_color=PITCH_BG, line_color=PITCH_LINE_COLOR,
        linewidth=1.5, stripe=False, goal_type='box',
        pad_top=2, pad_bottom=2, pad_left=2, pad_right=2,
    )
    fig_mpl, ax = pitch.draw(figsize=(4.5, 3.0))

    n_total = max(n_total, 1)
    has_end = 'Pass End X' in passes.columns and 'Pass End Y' in passes.columns

    # Pre-compute all sent percentages for scaling cell backgrounds
    sent_grid = {}
    for x0, x1 in zip(_X_BOUNDS[:-1], _X_BOUNDS[1:]):
        for y0, y1 in zip(_Y_BOUNDS[:-1], _Y_BOUNDS[1:]):
            m = ((passes['x'] >= x0) & (passes['x'] < x1) &
                 (passes['y'] >= y0) & (passes['y'] < y1))
            sent_grid[(x0, y0)] = m.sum() / n_total * 100
    max_sent = max(sent_grid.values()) if sent_grid else 1

    for x0, x1 in zip(_X_BOUNDS[:-1], _X_BOUNDS[1:]):
        for y0, y1 in zip(_Y_BOUNDS[:-1], _Y_BOUNDS[1:]):
            sent_pct = sent_grid[(x0, y0)]

            if has_end:
                rm = ((passes['Pass End X'] >= x0) & (passes['Pass End X'] < x1) &
                      (passes['Pass End Y'] >= y0) & (passes['Pass End Y'] < y1))
                recv_pct = rm.sum() / n_total * 100
            else:
                recv_pct = 0.0

            # Heat fill scaled by sent %
            alpha = 0.06 + 0.40 * (sent_pct / max(max_sent, 1))
            ax.add_patch(Rectangle(
                (x0, y0), x1 - x0, y1 - y0,
                facecolor=COLORS['gold'], alpha=alpha, linewidth=0, zorder=1,
            ))

            cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
            ax.text(cx, cy + 5.5, f'S  {sent_pct:.0f}%',
                    ha='center', va='center', fontsize=6.5,
                    color=COLORS['gold'], fontweight='bold', zorder=2)
            ax.text(cx, cy - 5.5, f'R  {recv_pct:.0f}%',
                    ha='center', va='center', fontsize=6.5,
                    color='white', fontweight='bold', zorder=2)

    # Third + band dividers
    for xb in [100/3, 200/3]:
        ax.axvline(xb, color='white', linewidth=0.8, linestyle='--', alpha=0.25, zorder=3)
    for yb in [100/3, 200/3]:
        ax.axhline(yb, color='white', linewidth=0.8, linestyle='--', alpha=0.25, zorder=3)

    fig_mpl.text(0.5, 0.01, 'S = Sent   R = Received',
                 ha='center', va='bottom', fontsize=5.5,
                 color='#aaaaaa', style='italic',
                 transform=fig_mpl.transFigure)

    buf = io.BytesIO()
    fig_mpl.savefig(buf, format='png', dpi=130, bbox_inches='tight',
                    pad_inches=0.05, facecolor=PITCH_BG)
    buf.seek(0)
    result = base64.b64encode(buf.read()).decode()
    plt.close(fig_mpl)
    return result


def _stats_numbers_children(passes: pd.DataFrame) -> list:
    """2×2 stat cards — returned as a list for use as div children."""
    n_total = len(passes)
    n_suc   = int(passes['outcome'].eq(1).sum()) if 'outcome' in passes.columns else 0
    acc     = round(n_suc / max(n_total, 1) * 100, 1)

    # Progressive: successful pass advancing ≥25% of pitch length
    if 'Pass End X' in passes.columns and 'x' in passes.columns:
        mask_suc  = passes['outcome'].eq(1) if 'outcome' in passes.columns \
                    else pd.Series(True, index=passes.index)
        n_prog = int((mask_suc & ((passes['Pass End X'] - passes['x']) >= 25)).sum())
    else:
        n_prog = 0

    # Key passes: qualifier column 'Key Pass' == 1
    n_key = int(pd.to_numeric(passes['Key Pass'], errors='coerce').eq(1).sum()) \
            if 'Key Pass' in passes.columns else 0

    def _card(value, label, color):
        return html.Div([
            html.Div(str(value), style={
                'color': color, 'fontWeight': '800',
                'fontSize': '1.5rem', 'lineHeight': '1.1',
            }),
            html.Div(label, style={
                'color': COLORS['text_secondary'],
                'fontSize': '0.63rem', 'fontWeight': '600',
                'letterSpacing': '0.6px', 'textTransform': 'uppercase',
                'marginTop': '3px',
            }),
        ], style={
            'backgroundColor': COLORS['dark_secondary'],
            'border': f'1px solid {COLORS["dark_border"]}',
            'borderRadius': '6px',
            'padding': '10px 12px',
            'flex': '1',
        })

    def _row(*cards):
        return html.Div(list(cards), style={'display': 'flex', 'gap': '6px', 'marginBottom': '6px'})

    return [
        _row(_card(n_total,   'Total',       GOLD),
             _card(f'{acc}%', 'Accuracy',    HOME_COLOR)),
        _row(_card(n_prog,    'Progressive', HOME_COLOR),
             _card(n_key,     'Key Passes',  AWAY_COLOR)),
    ]


def _stats_col_children(initial_passes: pd.DataFrame, n_total_passes: int,
                        initial_touches: pd.DataFrame | None = None) -> list:
    """Children for the stats column inside the combined panel.
    The checkbox and image IDs are static; only their sub-properties are
    updated by the callback so state is never reset.
    """
    if initial_touches is None:
        initial_touches = pd.DataFrame()
    zone_src = f'data:image/png;base64,{_build_zone_pitch_image(initial_passes, n_total_passes)}'
    return [
        html.Div("Pass Stats", style=_SECTION_TITLE),
        html.Div(style={'marginTop': '10px'}),
        html.Div(id='buildup-stats-numbers', children=_stats_numbers_children(initial_passes)),
        html.Hr(style={'borderColor': COLORS['dark_border'], 'margin': '12px 0 8px'}),
        html.Div([
            html.Div("Pass Distribution",
                     style={**_SECTION_TITLE, 'borderBottom': 'none', 'paddingBottom': '0', 'flex': '1'}),
            dcc.Checklist(
                id='buildup-dist-total',
                options=[{'label': ' All passes', 'value': 'total'}],
                value=[],
                inputStyle={'cursor': 'pointer', 'accentColor': COLORS['gold']},
                labelStyle={'color': COLORS['text_secondary'], 'fontSize': '0.60rem', 'cursor': 'pointer'},
            ),
        ], style={'display': 'flex', 'alignItems': 'center', 'gap': '6px', 'marginBottom': '6px'}),
        html.Img(
            id='buildup-zone-pitch-img',
            src=zone_src,
            style={'width': '100%', 'borderRadius': '4px'},
        ),
        html.Hr(style={'borderColor': COLORS['dark_border'], 'margin': '12px 0 8px'}),
        html.Div(id='buildup-top5-prog',
                 children=_top5_progressive_children(initial_passes)),
        html.Hr(style={'borderColor': COLORS['dark_border'], 'margin': '12px 0 8px'}),
        html.Div(id='buildup-top5-poss',
                 children=_top5_poss_children(initial_touches)),
    ]


# =============================================================================
# Touch-map helpers
# =============================================================================

def _filter_touches(bar_events: pd.DataFrame, *,
                    players, h1_range, h2_range) -> pd.DataFrame:
    """Return BAR events filtered by player and half-time ranges."""
    df = bar_events.copy()
    if players and 'player_name' in df.columns:
        df = df[df['player_name'].isin(players)]
    if 'period_id' in df.columns and 'time_min' in df.columns:
        h1_lo, h1_hi = h1_range
        h2_lo, h2_hi = h2_range
        m1 = (df['period_id'] == 1) & (df['time_min'] >= h1_lo) & (df['time_min'] <= h1_hi)
        m2 = (df['period_id'] == 2) & (df['time_min'] >= h2_lo) & (df['time_min'] <= h2_hi)
        df = df[m1 | m2]
    return df.dropna(subset=['x', 'y'])


def _touch_map_src(touches: pd.DataFrame) -> str:
    return render_lsc_heatmap_img(
        touches['x'].tolist(),
        touches['y'].tolist(),
        COLORS['primary_blue'],
        show_zone_pcts=True,
        text_color=COLORS['gold'],
    )


def _top5_poss_children(touches: pd.DataFrame) -> list:
    """Top-5 players by possession touch share, styled as a ranked list."""
    if touches.empty or 'player_name' not in touches.columns:
        return [html.P("No data", style={'color': COLORS['text_secondary'], 'fontSize': '0.75rem'})]

    n_total = max(len(touches), 1)
    top5 = (
        touches.groupby('player_name').size()
        .sort_values(ascending=False)
        .head(5)
        .reset_index(name='count')
    )
    top5['pct'] = (top5['count'] / n_total * 100).round(1)

    rows = []
    for rank, row in enumerate(top5.itertuples(), start=1):
        rows.append(html.Div([
            html.Span(f"{rank}", style={
                'color': COLORS['gold'], 'fontWeight': '800',
                'fontSize': '0.85rem', 'minWidth': '18px',
            }),
            html.Span(row.player_name, style={
                'color': 'white', 'fontSize': '0.72rem',
                'flex': '1', 'overflow': 'hidden',
                'textOverflow': 'ellipsis', 'whiteSpace': 'nowrap',
            }),
            html.Span(f"{row.pct}%", style={
                'color': COLORS['gold'], 'fontWeight': '700',
                'fontSize': '0.75rem', 'marginLeft': '6px',
            }),
        ], style={
            'display': 'flex', 'alignItems': 'center', 'gap': '8px',
            'padding': '6px 0',
            'borderBottom': f'1px solid {COLORS["dark_border"]}',
        }))

    return [
        html.Div("Top Possession", style={
            **_SECTION_TITLE,
            'borderBottom': f'1px solid {COLORS["dark_border"]}',
            'marginBottom': '8px',
        }),
        *rows,
    ]


# =============================================================================
# Pass-network helpers
# =============================================================================

def _build_network_bar(bar_events: pd.DataFrame):
    """Pass-network nodes + edges from (already filtered) BAR events."""
    cols = ['player_name', 'event_type', 'outcome', 'x', 'y',
            'period_id', 'time_min', 'time_sec']
    ev = bar_events[[c for c in cols if c in bar_events.columns]].copy()
    ev = ev.dropna(subset=['player_name', 'x', 'y'])
    ev = ev.sort_values(['period_id', 'time_min', 'time_sec']).reset_index(drop=True)

    edges: dict = {}
    for i in range(len(ev) - 1):
        row = ev.iloc[i]
        nxt = ev.iloc[i + 1]
        if (row['event_type'] == 'Pass' and row.get('outcome') == 1
                and pd.notna(nxt.get('player_name'))):
            a, b = str(row['player_name']), str(nxt['player_name'])
            if a != b:
                edges[(a, b)] = edges.get((a, b), 0) + 1

    edges = {k: v for k, v in edges.items() if v >= 2}

    pass_ev = ev[ev['event_type'] == 'Pass']
    if pass_ev.empty:
        return pd.DataFrame(), {}

    nodes = (
        pass_ev.groupby('player_name')
        .agg(x=('x', 'mean'), y=('y', 'mean'))
        .reset_index()
    )

    inv: dict = {}
    for (a, b), cnt in edges.items():
        inv[a] = inv.get(a, 0) + cnt
        inv[b] = inv.get(b, 0) + cnt
    nodes['involvement'] = nodes['player_name'].map(lambda p: inv.get(p, 1))

    if len(nodes) > 1 and nodes['involvement'].max() > nodes['involvement'].min():
        sc = MinMaxScaler(feature_range=(14, 36))
        nodes['size'] = sc.fit_transform(nodes[['involvement']]).flatten()
    else:
        nodes['size'] = 22.0

    nodes['label'] = nodes['player_name'].apply(
        lambda n: n.split()[-1] if isinstance(n, str) else n)
    return nodes, edges


def _network_fig_bar(nodes: pd.DataFrame, edges: dict) -> go.Figure:
    """Plotly pass-network figure using buildup pitch background."""
    fig = go.Figure()
    _add_pitch_background(fig)

    if edges:
        max_cnt = max(edges.values())
        for (a, b), cnt in edges.items():
            an = nodes[nodes['player_name'] == a]
            bn = nodes[nodes['player_name'] == b]
            if an.empty or bn.empty:
                continue
            x0, y0 = float(an.iloc[0]['x']), float(an.iloc[0]['y'])
            x1, y1 = float(bn.iloc[0]['x']), float(bn.iloc[0]['y'])
            width = 1.0 + (cnt / max_cnt) * 5.0

            if (b, a) in edges:
                dx, dy  = x1 - x0, y1 - y0
                length  = (dx**2 + dy**2) ** 0.5 or 1.0
                ox, oy  = -dy / length * 2.5, dx / length * 2.5
                xm, ym  = (x0 + x1) / 2 + ox, (y0 + y1) / 2 + oy
                t       = np.linspace(0, 1, 25)
                cx_pts  = (1-t)**2 * x0 + 2*(1-t)*t * xm + t**2 * x1
                cy_pts  = (1-t)**2 * y0 + 2*(1-t)*t * ym + t**2 * y1
            else:
                cx_pts, cy_pts = [x0, x1], [y0, y1]
                xm, ym = (x0 + x1) / 2, (y0 + y1) / 2

            fig.add_trace(go.Scatter(
                x=cx_pts, y=cy_pts, mode='lines',
                line=dict(color=COLORS['primary_blue'], width=width),
                opacity=0.55, hoverinfo='skip', showlegend=False,
            ))
            fig.add_trace(go.Scatter(
                x=[xm], y=[ym], mode='markers',
                marker=dict(size=14, color='rgba(0,0,0,0)', opacity=0),
                customdata=[[str(a), str(b), cnt]],
                hovertemplate=(
                    '<b>%{customdata[0]} → %{customdata[1]}</b><br>'
                    'Passes: %{customdata[2]}<extra></extra>'
                ),
                showlegend=False,
            ))

    if not nodes.empty:
        fig.add_trace(go.Scatter(
            x=nodes['x'], y=nodes['y'],
            mode='markers+text',
            marker=dict(size=nodes['size'], color=COLORS['primary_blue'],
                        line=dict(width=2, color='white')),
            text=nodes['label'],
            textposition='middle center',
            textfont=dict(size=8, color='white', family='Arial Black'),
            customdata=nodes[['player_name', 'involvement']].values,
            hovertemplate=(
                '<b>%{customdata[0]}</b><br>'
                'Involvement: %{customdata[1]:.0f} connections<extra></extra>'
            ),
            showlegend=False,
        ))

    _add_attack_direction(fig)
    fig.update_layout(
        **PITCH_AXIS_FULL,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font=dict(color='#E8E9ED', size=12, family='Arial, sans-serif'),
        margin=dict(l=0, r=0, t=36, b=0),
        showlegend=False,
        height=520,
        uirevision='buildup-network',
        hovermode='closest',
    )
    return fig


def _pass_matrix_fig(bar_events: pd.DataFrame) -> go.Figure:
    """Square pass-count heatmap between top-11 Barça players (incl. GK)."""
    ev = bar_events[
        [c for c in ['player_name', 'event_type', 'outcome',
                     'period_id', 'time_min', 'time_sec']
         if c in bar_events.columns]
    ].copy()
    ev = ev.dropna(subset=['player_name'])
    ev = ev.sort_values(['period_id', 'time_min', 'time_sec']).reset_index(drop=True)

    counts: dict = {}
    for i in range(len(ev) - 1):
        row = ev.iloc[i]
        nxt = ev.iloc[i + 1]
        if (row['event_type'] == 'Pass' and row.get('outcome') == 1
                and pd.notna(nxt.get('player_name'))):
            a, b = str(row['player_name']), str(nxt['player_name'])
            if a != b:
                counts[(a, b)] = counts.get((a, b), 0) + 1

    empty_fig = go.Figure()
    empty_fig.update_layout(paper_bgcolor='rgba(0,0,0,0)',
                            plot_bgcolor=PITCH_BG, height=520)
    if not counts:
        return empty_fig

    involvement: dict = {}
    for (a, b), cnt in counts.items():
        involvement[a] = involvement.get(a, 0) + cnt
        involvement[b] = involvement.get(b, 0) + cnt

    top_players = sorted(involvement, key=involvement.get, reverse=True)[:11]

    n         = len(top_players)
    matrix    = np.zeros((n, n))
    total_all = sum(counts.values()) or 1
    pct_matrix = np.zeros((n, n))
    for i, a in enumerate(top_players):
        for j, b in enumerate(top_players):
            if i != j:
                c = counts.get((a, b), 0)
                matrix[i][j]    = c
                pct_matrix[i][j] = c / total_all * 100
    np.fill_diagonal(matrix, np.nan)
    np.fill_diagonal(pct_matrix, np.nan)

    barca_cs = [
        [0.0, '#151932'],
        [0.5, COLORS['primary_blue']],
        [1.0, COLORS['gold']],
    ]

    text_matrix = [
        ['' if i == j else str(int(matrix[i][j])) for j in range(n)]
        for i in range(n)
    ]

    fig = go.Figure(go.Heatmap(
        z=matrix,
        x=top_players,
        y=top_players,
        colorscale=barca_cs,
        showscale=False,
        text=text_matrix,
        texttemplate='%{text}',
        textfont=dict(size=9, color='white'),
        customdata=pct_matrix,
        hovertemplate='<b>%{y} → %{x}</b><br>Passes: %{z:.0f} (%{customdata:.1f}% of team)<extra></extra>',
    ))
    fig.update_layout(
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor=PITCH_BG,
        font=dict(color=COLORS['text_primary'], size=10, family='Arial, sans-serif'),
        margin=dict(l=40, r=10, t=8, b=40),
        height=520,
        xaxis=dict(
            tickfont=dict(size=8, color=COLORS['text_secondary']),
            showgrid=False,
            constrain='domain',
            title=dict(text='Receiver', font=dict(size=9, color=COLORS['text_secondary'])),
        ),
        yaxis=dict(
            tickfont=dict(size=8, color=COLORS['text_secondary']),
            showgrid=False,
            autorange='reversed',
            scaleanchor='x',
            constrain='domain',
            title=dict(text='Passer', font=dict(size=9, color=COLORS['text_secondary'])),
        ),
        uirevision='buildup-matrix',
    )
    return fig


def _top5_progressive_children(passes: pd.DataFrame) -> list:
    """Top-5 players by progressive-pass count.
    Progressive pass: successful pass where end_x − x ≥ 25 (≥25% of pitch).
    """
    if passes.empty or 'Pass End X' not in passes.columns:
        return [html.P("No data", style={'color': COLORS['text_secondary'], 'fontSize': '0.75rem'})]

    mask_suc  = passes['outcome'].eq(1) if 'outcome' in passes.columns \
                else pd.Series(True, index=passes.index)
    mask_prog = (passes['Pass End X'] - passes['x']) >= 25
    prog = passes[mask_suc & mask_prog]

    if prog.empty or 'player_name' not in prog.columns:
        return [html.P("No data", style={'color': COLORS['text_secondary'], 'fontSize': '0.75rem'})]

    top5 = (
        prog.groupby('player_name').size()
        .sort_values(ascending=False)
        .head(5)
        .reset_index(name='count')
    )

    rows = []
    for rank, row in enumerate(top5.itertuples(), start=1):
        rows.append(html.Div([
            html.Span(f"{rank}", style={
                'color': COLORS['gold'], 'fontWeight': '800',
                'fontSize': '0.85rem', 'minWidth': '18px',
            }),
            html.Span(row.player_name, style={
                'color': 'white', 'fontSize': '0.72rem',
                'flex': '1', 'overflow': 'hidden',
                'textOverflow': 'ellipsis', 'whiteSpace': 'nowrap',
            }),
            html.Span(str(row.count), style={
                'color': COLORS['gold'], 'fontWeight': '700',
                'fontSize': '0.75rem', 'marginLeft': '6px',
            }),
        ], style={
            'display': 'flex', 'alignItems': 'center', 'gap': '8px',
            'padding': '6px 0',
            'borderBottom': f'1px solid {COLORS["dark_border"]}',
        }))

    return [
        html.Div("Top Progressive Passers", style={
            **_SECTION_TITLE,
            'borderBottom': f'1px solid {COLORS["dark_border"]}',
            'marginBottom': '4px',
        }),
        html.Div("(Successful passes advancing ≥ 25% of pitch)", style={
            'color': COLORS['text_secondary'],
            'fontSize': '0.58rem',
            'fontStyle': 'italic',
            'marginBottom': '8px',
        }),
        *rows,
    ]


# =============================================================================
# Zone-3 entry helpers
# =============================================================================

def _build_entries_bar(bar_events: pd.DataFrame, zone: str = 'final_third') -> pd.DataFrame:
    """Entries into final third or Zone 14/Half Spaces from BAR team events."""
    relevant_types = ['Pass', 'Take On', 'Ball touch']
    te_full = bar_events.sort_values(
        ['period_id', 'time_min', 'time_sec']).reset_index(drop=True)
    ev = (te_full[te_full['event_type'].isin(relevant_types)]
          .dropna(subset=['x', 'y'])
          .reset_index())  # 'index' col = row position in te_full

    entries = []
    for i in range(len(ev)):
        row   = ev.iloc[i]
        etype = row['event_type']
        start_x = float(row['x'])

        if etype == 'Pass':
            if pd.notna(row.get('Pass End X')):
                end_x = float(row['Pass End X'])
                end_y = float(row['Pass End Y'])
            else:
                continue
        else:
            if i + 1 < len(ev):
                nxt   = ev.iloc[i + 1]
                end_x = float(nxt['x'])
                end_y = float(nxt['y'])
            else:
                continue

        start_y   = float(row['y'])
        dest_zone = None

        if zone == 'final_third':
            if not (start_x < 66.67 and end_x >= 66.67):
                continue
        elif zone == 'zone14':
            in_z14 = (66.67 <= end_x <= 83.33) and (37 <= end_y <= 63)
            in_lhs = (end_x > 66.67) and (63 < end_y <= 79)
            in_rhs = (end_x > 66.67) and (21 <= end_y < 37)
            if not (in_z14 or in_lhs or in_rhs):
                continue
            dest_zone = ('Zone 14' if in_z14
                         else 'Left Half Space' if in_lhs
                         else 'Right Half Space')

        label_map = {'Pass': 'Pass', 'Take On': 'Dribble', 'Ball touch': 'Carry'}
        outcome  = row.get('outcome', None)
        te_idx   = int(row['index'])
        next_5   = te_full.iloc[te_idx + 1: te_idx + 6]
        led_to_shot = bool(next_5['event_type'].isin(_SHOT_TYPES).any()) if not next_5.empty else False
        led_to_goal = bool((next_5['event_type'] == 'Goal').any())       if not next_5.empty else False

        receiver_name = ''
        if etype == 'Pass' and outcome == 1 and te_idx + 1 < len(te_full):
            nxt_full = te_full.iloc[te_idx + 1]
            if pd.notna(nxt_full.get('player_name')):
                receiver_name = str(nxt_full['player_name'])

        entries.append({
            'player_name':   row.get('player_name', ''),
            'event_label':   label_map.get(etype, etype),
            'x':             start_x,
            'y':             start_y,
            'end_x':         end_x,
            'end_y':         end_y,
            'outcome':       outcome,
            'time_min':      row.get('time_min', 0),
            'time_sec':      row.get('time_sec', 0),
            'period_id':     row.get('period_id', 0),
            'dest_zone':     dest_zone,
            'led_to_shot':   led_to_shot,
            'led_to_goal':   led_to_goal,
            'receiver_name': receiver_name,
        })

    if not entries:
        return pd.DataFrame(columns=[
            'player_name', 'event_label', 'x', 'y', 'end_x', 'end_y',
            'outcome', 'time_min', 'time_sec', 'period_id',
            'dest_zone', 'led_to_shot', 'led_to_goal', 'receiver_name',
        ])
    return pd.DataFrame(entries)


def _entries_fig_bar(entries_df: pd.DataFrame, zone: str) -> go.Figure:
    """Interactive Plotly pitch figure for final-third / Zone-14 entries (BAR only)."""
    fig = go.Figure()
    _add_pitch_background(fig)

    if not entries_df.empty:
        entries_df = entries_df.copy()
        entries_df['time_display'] = entries_df.apply(
            lambda r: f"{int(r['time_min'])}:{int(r['time_sec']):02d}", axis=1)
        entries_df['outcome_label'] = entries_df['outcome'].map(
            {1: '✓ Successful', 0: '✗ Unsuccessful'}).fillna('—')
        entries_df['shot_label'] = entries_df.apply(
            lambda r: '<br>⚽ Led to Goal' if r.get('led_to_goal', False)
                      else ('<br>🎯 Led to Shot' if r.get('led_to_shot', False) else ''),
            axis=1)
        if 'receiver_name' not in entries_df.columns:
            entries_df['receiver_name'] = ''

        if zone == 'zone14' and 'dest_zone' in entries_df.columns:
            color_iter = _ZONE14_COLORS.items()
            group_col  = 'dest_zone'
        else:
            color_iter = _ENTRY_COLORS.items()
            group_col  = 'event_label'

        for group_name, ecolor in color_iter:
            subset = entries_df[entries_df[group_col] == group_name]
            if subset.empty:
                continue

            passes_sub    = subset[subset['event_label'] == 'Pass']
            nonpasses_sub = subset[subset['event_label'] != 'Pass']

            # Arrows / lines
            if zone == 'zone14':
                for _, r in passes_sub.iterrows():
                    fig.add_annotation(
                        x=r['end_x'], y=r['end_y'], ax=r['x'], ay=r['y'],
                        xref='x', yref='y', axref='x', ayref='y',
                        showarrow=True, arrowhead=2, arrowsize=1.5,
                        arrowwidth=2, arrowcolor=ecolor, opacity=0.65)
                if not nonpasses_sub.empty:
                    xs, ys = [], []
                    for _, r in nonpasses_sub.iterrows():
                        xs.extend([r['x'], r['end_x'], None])
                        ys.extend([r['y'], r['end_y'], None])
                    fig.add_trace(go.Scatter(
                        x=xs, y=ys, mode='lines',
                        line=dict(color=ecolor, width=2, dash='dash'),
                        showlegend=False, hoverinfo='skip'))
            else:
                for _, r in subset.iterrows():
                    fig.add_annotation(
                        x=r['end_x'], y=r['end_y'], ax=r['x'], ay=r['y'],
                        xref='x', yref='y', axref='x', ayref='y',
                        showarrow=True, arrowhead=2, arrowsize=1.5,
                        arrowwidth=2, arrowcolor=ecolor, opacity=0.65)

            legend_name  = f'{group_name} ({len(subset)})'
            legend_shown = False

            # Pass hover markers
            if not passes_sub.empty:
                if zone == 'zone14':
                    cd = passes_sub[['player_name', 'receiver_name', 'event_label',
                                     'time_display', 'outcome_label', 'shot_label']].values
                    ht = (f'<b>{group_name}</b><br>'
                          'Pass: %{customdata[0]} → %{customdata[1]}<br>'
                          'Time: %{customdata[3]}<br>%{customdata[4]}%{customdata[5]}'
                          '<extra></extra>')
                else:
                    cd = passes_sub[['player_name', 'receiver_name',
                                     'time_display', 'outcome_label', 'shot_label']].values
                    ht = (f'<b>{group_name}</b><br>'
                          '%{customdata[0]} → %{customdata[1]}<br>'
                          'Time: %{customdata[2]}<br>%{customdata[3]}%{customdata[4]}'
                          '<extra></extra>')
                fig.add_trace(go.Scatter(
                    x=passes_sub['end_x'], y=passes_sub['end_y'], mode='markers',
                    marker=dict(size=8, color=ecolor, line=dict(width=1.5, color='white')),
                    customdata=cd, hovertemplate=ht,
                    name=legend_name, showlegend=True, legendgroup=group_name))
                legend_shown = True

            # Non-pass hover markers
            if not nonpasses_sub.empty:
                if zone == 'zone14':
                    cd = nonpasses_sub[['player_name', 'event_label',
                                        'time_display', 'outcome_label', 'shot_label']].values
                    ht = (f'<b>{group_name}</b><br>'
                          '%{customdata[1]}: %{customdata[0]}<br>'
                          'Time: %{customdata[2]}<br>%{customdata[3]}%{customdata[4]}'
                          '<extra></extra>')
                else:
                    cd = nonpasses_sub[['player_name',
                                        'time_display', 'outcome_label', 'shot_label']].values
                    ht = (f'<b>{group_name}</b><br>'
                          '%{customdata[0]}<br>'
                          'Time: %{customdata[1]}<br>%{customdata[2]}%{customdata[3]}'
                          '<extra></extra>')
                fig.add_trace(go.Scatter(
                    x=nonpasses_sub['end_x'], y=nonpasses_sub['end_y'], mode='markers',
                    marker=dict(size=8, color=ecolor, line=dict(width=1.5, color='white')),
                    customdata=cd, hovertemplate=ht,
                    name=legend_name if not legend_shown else '',
                    showlegend=not legend_shown, legendgroup=group_name))

    # Zone boundaries
    if zone == 'final_third':
        fig.add_shape(type='line', x0=66.67, y0=0, x1=66.67, y1=100,
                      line=dict(color='yellow', width=3, dash='dash'))
        fig.add_annotation(x=83, y=96, text='Final Third', showarrow=False,
                           font=dict(color='yellow', size=11, family='Arial Black'),
                           bgcolor='rgba(0,0,0,0.5)', borderpad=4)
    elif zone == 'zone14':
        fig.add_shape(type='rect', x0=66.67, y0=37, x1=83.33, y1=63,
                      line=dict(color='#ff1493', width=2, dash='dash'),
                      fillcolor='rgba(255,20,147,0.08)')
        fig.add_annotation(x=75, y=50, text='Zone 14', showarrow=False,
                           font=dict(color='#ff1493', size=10, family='Arial Black'),
                           bgcolor='rgba(0,0,0,0.5)', borderpad=3)
        fig.add_shape(type='rect', x0=66.67, y0=63, x1=100, y1=79,
                      line=dict(color='#00ffff', width=2, dash='dash'),
                      fillcolor='rgba(0,255,255,0.08)')
        fig.add_annotation(x=83, y=71, text='Left HS', showarrow=False,
                           font=dict(color='#00ffff', size=10, family='Arial Black'),
                           bgcolor='rgba(0,0,0,0.5)', borderpad=3)
        fig.add_shape(type='rect', x0=66.67, y0=21, x1=100, y1=37,
                      line=dict(color='#ffd700', width=2, dash='dash'),
                      fillcolor='rgba(255,215,0,0.08)')
        fig.add_annotation(x=83, y=29, text='Right HS', showarrow=False,
                           font=dict(color='#ffd700', size=10, family='Arial Black'),
                           bgcolor='rgba(0,0,0,0.5)', borderpad=3)

    _add_attack_direction(fig)
    fig.update_layout(
        **PITCH_AXIS_FULL,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font=dict(color='#E8E9ED', size=12, family='Arial, sans-serif'),
        margin=dict(l=0, r=0, t=36, b=0),
        height=480,
        uirevision=f'buildup-entries-{zone}',
        hovermode='closest',
        legend=dict(
            orientation='v', x=0.01, xanchor='left', y=0.99, yanchor='top',
            bgcolor='rgba(0,0,0,0.55)',
            font=dict(color=COLORS['text_primary'], size=9),
        ),
    )
    return fig


# =============================================================================
# Public builder
# =============================================================================

def build_buildup_tab(season, competitions, match_ids=None) -> html.Div:
    """Build the full Build-up Pass Map tab content."""
    events = get_all_events(season)
    if events.empty:
        return html.P("No data available.", style={'color': COLORS['text_secondary']})

    if competitions and 'competition' in events.columns:
        events = events[events['competition'].isin(competitions)]
    if match_ids:
        events = events[events['match_id'].isin(match_ids)]

    passes = _get_passes(events)
    if passes.empty:
        return html.P("No Barcelona pass data.", style={'color': COLORS['text_secondary']})

    player_opts = []
    if 'player_name' in passes.columns:
        names       = passes['player_name'].dropna().unique()
        player_opts = sorted([{'label': n, 'value': n} for n in names],
                             key=lambda d: d['label'])

    initial = _apply_filters(
        passes,
        outcomes=[0, 1], start_thirds=None, end_thirds=None,
        bands=None, players=None,
        h1_range=(0, 50), h2_range=(45, 100),
    )

    # Possession touch map — initial render (no player/half filter applied yet)
    bar_events  = events[events['team_code'] == 'BAR']
    init_touches = _filter_touches(bar_events, players=None,
                                   h1_range=(0, 50), h2_range=(45, 100))

    init_nodes, init_edges = _build_network_bar(bar_events)

    pass_map_children = [
        html.Div([
            html.Div("Pass Map",
                     style={**_SECTION_TITLE, 'borderBottom': 'none',
                            'paddingBottom': '0', 'flex': '1'}),
            dcc.Checklist(
                id='buildup-prog-only',
                options=[{'label': ' Progressive only', 'value': 'prog'}],
                value=[],
                inputStyle={'cursor': 'pointer', 'accentColor': COLORS['gold']},
                labelStyle={'color': COLORS['text_secondary'],
                            'fontSize': '0.60rem', 'cursor': 'pointer'},
            ),
        ], style={
            'display': 'flex', 'alignItems': 'center', 'gap': '6px',
            'marginBottom': '6px',
            'borderBottom': f'1px solid {COLORS["dark_border"]}',
            'paddingBottom': '8px',
        }),
        html.Div(style={'marginBottom': '10px'}),
        dcc.Loading(
            type='circle', color=COLORS['gold'],
            children=dcc.Graph(
                id='buildup-pitch-graph',
                figure=_build_pass_fig(initial),
                config=CHART_CONFIG,
                style={'width': '100%'},
            ),
        ),
        html.Hr(style={'borderColor': COLORS['dark_border'], 'margin': '16px 0 12px'}),
        html.Div("Possession Touch Map", style=_SECTION_TITLE),
        html.Div(style={'marginBottom': '8px'}),
        dcc.Loading(
            type='circle', color=COLORS['gold'],
            children=html.Img(
                id='buildup-touch-map-img',
                src=_touch_map_src(init_touches),
                style={'width': '100%', 'borderRadius': '6px'},
            ),
        ),
    ]

    # Single scrollable panel: top split (pass map | stats), then full-width network row
    combined = html.Div([
        dbc.Row([
            dbc.Col(pass_map_children, md=8),
            dbc.Col(
                _stats_col_children(initial, len(passes), init_touches),
                md=4,
                style={
                    'borderLeft': f'1px solid {COLORS["dark_border"]}',
                    'paddingLeft': '16px',
                },
            ),
        ], align='start', className='g-0'),
        html.Hr(style={'borderColor': COLORS['dark_border'], 'margin': '16px 0 12px'}),
        html.Div("Pass Network", style=_SECTION_TITLE),
        html.Div(style={'marginBottom': '8px'}),
        dbc.Row([
            dbc.Col(
                dcc.Loading(
                    type='circle', color=COLORS['gold'],
                    children=dcc.Graph(
                        id='buildup-network-fig',
                        figure=_network_fig_bar(init_nodes, init_edges),
                        config=CHART_CONFIG,
                        style={'width': '100%'},
                    ),
                ),
                md=7,
            ),
            dbc.Col(
                dcc.Loading(
                    type='circle', color=COLORS['gold'],
                    children=dcc.Graph(
                        id='buildup-matrix-fig',
                        figure=_pass_matrix_fig(bar_events),
                        config=CHART_CONFIG,
                        style={'width': '100%'},
                    ),
                ),
                md=5,
            ),
        ], align='start', className='g-0'),
        html.Hr(style={'borderColor': COLORS['dark_border'], 'margin': '16px 0 12px'}),
        html.Div("Zone 3", style=_SECTION_TITLE),
        html.Div(style={'marginBottom': '8px'}),
        dbc.Row([
            dbc.Col([
                html.Div("Entries into Final Third",
                         style={**_SECTION_TITLE, 'borderBottom': 'none',
                                'paddingBottom': '4px', 'fontSize': '0.72rem'}),
                dcc.Loading(
                    type='circle', color=COLORS['gold'],
                    children=dcc.Graph(
                        id='buildup-ft-fig',
                        figure=_entries_fig_bar(
                            _build_entries_bar(bar_events, 'final_third'), 'final_third'),
                        config=CHART_CONFIG,
                        style={'width': '100%'},
                    ),
                ),
            ], md=6),
            dbc.Col([
                html.Div("Zone 14 & Half Spaces",
                         style={**_SECTION_TITLE, 'borderBottom': 'none',
                                'paddingBottom': '4px', 'fontSize': '0.72rem'}),
                dcc.Loading(
                    type='circle', color=COLORS['gold'],
                    children=dcc.Graph(
                        id='buildup-z14-fig',
                        figure=_entries_fig_bar(
                            _build_entries_bar(bar_events, 'zone14'), 'zone14'),
                        config=CHART_CONFIG,
                        style={'width': '100%'},
                    ),
                ),
            ], md=6),
        ], align='start', className='g-3'),
    ], style=_PANEL_STYLE)

    return html.Div(
        dbc.Row([
            dbc.Col(_filter_panel(player_opts), md=3),
            dbc.Col(combined,                   md=9),
        ], align='start', className='g-3'),
    )


# =============================================================================
# Callbacks
# =============================================================================

def register_buildup_callbacks(app) -> None:
    """Wire all filter controls to the interactive pass map and stats panel."""

    _EMPTY_SRC = 'data:image/png;base64,'

    @app.callback(
        Output('buildup-pitch-graph',    'figure'),
        Output('buildup-stats-numbers',  'children'),
        Output('buildup-zone-pitch-img', 'src'),
        Output('buildup-touch-map-img',  'src'),
        Output('buildup-network-fig',    'figure'),
        Output('buildup-matrix-fig',     'figure'),
        Output('buildup-top5-prog',      'children'),
        Output('buildup-top5-poss',      'children'),
        Output('buildup-ft-fig',         'figure'),
        Output('buildup-z14-fig',        'figure'),
        Input('buildup-outcome',         'value'),
        Input('buildup-start-third',     'value'),
        Input('buildup-end-third',       'value'),
        Input('buildup-bands',           'value'),
        Input('buildup-h1-time',         'value'),
        Input('buildup-h2-time',         'value'),
        Input('buildup-player-filter',   'value'),
        Input('buildup-dist-total',      'value'),
        Input('buildup-prog-only',       'value'),
        State('ta-competition-selector', 'value'),
        State('ta-venue-selector',       'value'),
        State('ta-selected-matches',     'data'),
        State('ta-match-data',           'data'),
        prevent_initial_call=True,
    )
    def _update(outcomes, start_thirds, end_thirds, bands,
                h1_range, h2_range, players, dist_total, prog_only,
                competition, venue, match_ids, match_data):

        empty = pd.DataFrame()
        def _empty():
            return (_build_pass_fig(empty), _stats_numbers_children(empty),
                    _EMPTY_SRC, _EMPTY_SRC,
                    go.Figure(), go.Figure(), [], [],
                    go.Figure(), go.Figure())

        events = get_all_events(CURRENT_SEASON)
        if events.empty:
            return _empty()

        comps = _normalize_competitions(competition)
        if comps and 'competition' in events.columns:
            events = events[events['competition'].isin(comps)]

        effective_ids = match_ids if match_ids else None
        if effective_ids == []:
            effective_ids = None

        if venue and venue != 'All' and match_data:
            is_home   = (venue == 'Home')
            venue_ids = [m['match_id'] for m in match_data if m.get('is_home') == is_home]
            effective_ids = (
                venue_ids if effective_ids is None
                else list(set(effective_ids) & set(venue_ids))
            )

        if effective_ids:
            events = events[events['match_id'].isin(effective_ids)]

        passes = _get_passes(events)
        if passes.empty:
            return _empty()

        n_all    = len(passes)
        _h1      = tuple(h1_range) if h1_range else (0,  50)
        _h2      = tuple(h2_range) if h2_range else (45, 100)

        filtered = _apply_filters(
            passes,
            outcomes=outcomes         or [0, 1],
            start_thirds=start_thirds or None,
            end_thirds=end_thirds     or None,
            bands=bands               or None,
            players=players           or None,
            h1_range=_h1,
            h2_range=_h2,
        )

        # Progressive-only filter applies to the pass map figure only
        if prog_only and 'Pass End X' in filtered.columns:
            _suc  = filtered['outcome'].eq(1) if 'outcome' in filtered.columns \
                    else pd.Series(True, index=filtered.index)
            plot_passes = filtered[_suc & ((filtered['Pass End X'] - filtered['x']) >= 25)]
        else:
            plot_passes = filtered

        use_total  = bool(dist_total)
        n_for_zone = n_all if use_total else len(filtered)
        zone_src   = f'data:image/png;base64,{_build_zone_pitch_image(filtered, n_for_zone)}'

        bar_events = events[events['team_code'] == 'BAR']

        # Touch map / top-5 possession: player + half filters only
        touches   = _filter_touches(bar_events, players=players or None,
                                    h1_range=_h1, h2_range=_h2)
        touch_src = _touch_map_src(touches) if not touches.empty else _EMPTY_SRC

        # Network / matrix / Zone-3: apply ALL pass filters to pass events
        # so that outcome, start-third, end-third and band selectors affect
        # every plot; non-pass events (carries, dribbles) keep player+half only.
        if not touches.empty:
            _pm  = touches['event_type'] == 'Pass'
            _bp  = touches[_pm].copy()
            if not _bp.empty and 'Pass End X' in _bp.columns:
                _bp = PassMap.filter(
                    _bp,
                    outcomes=outcomes         or [0, 1],
                    start_thirds=start_thirds or None,
                    end_thirds=end_thirds     or None,
                    bands=bands               or None,
                    h1_range=_h1, h2_range=_h2,
                    end_x_col='Pass End X',
                )
            filtered_bar = (
                pd.concat([_bp, touches[~_pm]], ignore_index=True)
                .sort_values(['period_id', 'time_min', 'time_sec'])
                .reset_index(drop=True)
            )
        else:
            filtered_bar = pd.DataFrame()

        net_nodes, net_edges = _build_network_bar(filtered_bar)
        net_fig = _network_fig_bar(net_nodes, net_edges)
        mat_fig = _pass_matrix_fig(filtered_bar)

        top5_prog = _top5_progressive_children(filtered)
        top5_poss = _top5_poss_children(touches)

        # Zone 3 entry plots — all pass filters + player/half for non-passes
        ft_fig  = _entries_fig_bar(_build_entries_bar(filtered_bar, 'final_third'), 'final_third')
        z14_fig = _entries_fig_bar(_build_entries_bar(filtered_bar, 'zone14'),      'zone14')

        return (_build_pass_fig(plot_passes), _stats_numbers_children(filtered),
                zone_src, touch_src, net_fig, mat_fig, top5_prog, top5_poss,
                ft_fig, z14_fig)
